services:
  app:
    image: php:8.2-apache
    volumes:
      - ..:/var/www/html
    ports:
      - "8080:80"
    command: ["bash", "-c", "apt-get update && apt-get install -y git && docker-php-ext-install mysqli pdo pdo_mysql && a2enmod rewrite && apache2-foreground"]

  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: heladeria_db
    ports:
      - "3306:3306"
